apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-api-deployment
  labels:
    app: url-shortener-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-api
  template:
    metadata:
      labels:
        app: url-shortener-api
    spec:
      # remove imagePullSecrets for local tests
      imagePullSecrets:
        - name: url-shortener-registry-key
      containers:
        - name: url-shortener-api
          # only for local tests -> imagePullPolicy: Never
          #imagePullPolicy: Never
          #image: url-shortener-api:1.0.0
          imagePullPolicy: Always
          image: 613032669857.dkr.ecr.us-east-1.amazonaws.com/url-shortener-registry:1.0.0
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 1
              memory: 2G
            limits:
              memory: 2G