version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1

  backend:
    depends_on:
      - mongodb
    environment:
      - PROPERTIES_FILE=application-uat
    image: url-shortener-api:1.0.0
    ports:
      - "8080:8080"
    networks:
      - network1

volumes:
  mongodata:

networks:
  network1:
